FROM tiangolo/uvicorn-gunicorn:python3.8-slim

# set work directory
WORKDIR /usr/src/app
# copy requirements file
COPY ./requirements.txt /usr/src/app/requirements.txt

RUN pip install -r requirements.txt

COPY . /usr/src/app/